import Head from "next/head";
import Header from "@/components/Header";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { api } from "@/services";
import ProductCard from "@/components/ProductCard";
import { DivShow } from "./style";

export interface IProducts {
  id: number;
  name: string;
  brand: string;
  description: string;
  photo: string;
  price: string;
  createdAt: string;
  updatedAt: string;
}

export const getStaticProps: GetStaticProps<{
  products: IProducts[];
}> = async () => {
  const res = await api.get("");

  const products: IProducts[] = res.data.products;

  return {
    props: {
      products,
    },
  };
};

export default function Home({
  products,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Mks Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <DivShow>
          {products.map((product) => (
            <ProductCard key={product.id} {...product} />
          ))}
        </DivShow>
      </main>
    </>
  );
}
